Add blog for SC UI
ServiceComb/ServiceComb.github.io pull request #113
Opened 2017-10-27 08:33 UTC by asifdxtreme

Preview: https://asifdxtreme.github.io/ServiceComb.github.io/docs/service-center-ui/

2017-10-29 03:56 UTC, eric-lee-ltk commented on _posts/cn/2017-10-28-service-centre-ui.md
> +For Viewing the Schema in Swagger from you can click on Test Schema button and you can view the completet details of Schema in Swagger form.
from -> form? completet -> complete

2017-10-29 03:56 UTC, eric-lee-ltk commented on _posts/cn/2017-10-28-service-centre-ui.md
> +This is the place where you can see the basic details of all the services which are registered in Service-Centre. You can see the details like MicroService Name, Application Name, Status, Version, Cr
Centre -> Center, besides, the center in filename is wrong too.

2017-10-29 03:56 UTC, eric-lee-ltk commented on _posts/2017-10-28-service-centre-ui.md
> +This is the place where you can see the basic details of all the services which are registered in Service-Centre. You can see the details like MicroService Name, Application Name, Status, Version, Cr
Centre -> Center, besides, the `center` in filename is wrong too.

2017-10-29 03:56 UTC, eric-lee-ltk commented on _posts/2017-10-28-service-centre-ui.md
> +For Viewing the Schema in Swagger from you can click on Test Schema button and you can view the completet details of Schema in Swagger form.
from -> form? completet -> complete

2017-10-29 03:56 UTC, eric-lee-ltk commented on _posts/2017-10-28-service-centre-ui.md
> +This is the place where you can see all the current running instances for the MicroService, you can get the list of endpoints and theri protocols.
theri -> their

2017-10-29 03:56 UTC, eric-lee-ltk commented on _posts/cn/2017-10-28-service-centre-ui.md
> +This is the place where you can see all the current running instances for the MicroService, you can get the list of endpoints and theri protocols.
theri -> their

2017-10-29 03:56 UTC, eric-lee-ltk commented on _posts/2017-10-28-service-centre-ui.md
> +---
The annotations in the images seem not to be clear enough. Can you please use another font or use a bigger size  for the annotations?

2017-10-29 13:40 UTC, eric-lee-ltk commented on _posts/2017-10-28-service-centre-ui.md
> +This is the place where we can get the list of all the Schema's for your MicroService, here you get options of viewing the Schema in Swagger form or Test the Schema on some particular instance. Here
please use `Schema\'s` instead of `Schema's` because there are some problem interpreting the `'` symbol.

2017-10-29 13:40 UTC, eric-lee-ltk commented on _posts/cn/2017-10-28-service-centre-ui.md
> +This is the place where we can get the list of all the Schema's for your MicroService, here you get options of viewing the Schema in Swagger form or Test the Schema on some particular instance. Here
please use `Schema\'s` instead of `Schema's` because there are some problem interpreting the `'` symbol.

2017-10-31 01:03 UTC, WillemJiang requested changes
@asifdxtreme  Could you fix the issues which were pointed out by Eric?

2017-11-02 04:30 UTC, asifdxtreme commented
@eric-lee-ltk Thanks for reviewing, I have updated my Commits based on your comments.

2017-11-03 15:08 UTC, WillemJiang approved these changes

2017-11-03 15:08 UTC, merged